default: &default
  secret_token: 061e5ba8aac4c84980a52c87f329dd1e
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %> 
  
development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
